/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_graphique_gouin;

/**
 *
 * @author gouin
 */
public class Fenêtre_Principale extends javax.swing.JFrame {

    /**
     * Creates new form Fenêtre_Principale
     */
    public Fenêtre_Principale() {
        initComponents();
        System.out.println("fenêtre créée");
        Msg_Bienvenue.setText("Bonjour le monde");
        Resultat.setVisible(false);
        Msg_Bye.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Msg_Bienvenue = new javax.swing.JLabel();
        Msg_Bye = new javax.swing.JLabel();
        bouton_valide = new javax.swing.JButton();
        ZonePrenom = new javax.swing.JTextField();
        demandePrenom = new javax.swing.JLabel();
        demandeSalaire = new javax.swing.JLabel();
        ZoneSalaire = new javax.swing.JTextField();
        Resultat0 = new javax.swing.JScrollPane();
        Resultat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Msg_Bienvenue.setText("Bonjour ! Nous allons faire un test");
        getContentPane().add(Msg_Bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, -1, -1));

        Msg_Bye.setText("Merci pour ton argent !!!");
        getContentPane().add(Msg_Bye, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        bouton_valide.setBackground(new java.awt.Color(0, 255, 0));
        bouton_valide.setText("Clique pour découvrir la vérité...");
        bouton_valide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_valideActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_valide, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        ZonePrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZonePrenomActionPerformed(evt);
            }
        });
        getContentPane().add(ZonePrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 240, -1));

        demandePrenom.setText("Entrez votre prénom :");
        getContentPane().add(demandePrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, -1, -1));

        demandeSalaire.setText("Entrez votre salaire (par mois) :");
        getContentPane().add(demandeSalaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, -1, -1));

        ZoneSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoneSalaireActionPerformed(evt);
            }
        });
        getContentPane().add(ZoneSalaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 182, -1));

        Resultat.setColumns(20);
        Resultat.setRows(5);
        Resultat0.setViewportView(Resultat);

        getContentPane().add(Resultat0, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 180, 310, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_valideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_valideActionPerformed
        // TODO add your handling code here:
        Msg_Bye.setText("Bonne fin de journée !");
        String a = ZonePrenom.getText();
        String Argent = ZoneSalaire.getText();
        int argent_entier = Integer.parseInt(Argent);
        if (argent_entier > 3000) {
            Resultat.setText("Mon brave " + a + " tu es considéré comme Riche...\nDonne moi ton fric tout de suite !!");
            Resultat.setVisible(true);
            Msg_Bye.setVisible(true);     
        }
        if (argent_entier <= 3000) {
            Resultat.setText("Mon brave " + a + " tu es considéré comme Pauvre...\nDonne moi ton argent...ou ce qui te reste...");
            Resultat.setVisible(true);
            Msg_Bye.setVisible(true);
        }
        
    }//GEN-LAST:event_bouton_valideActionPerformed

    private void ZoneSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoneSalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZoneSalaireActionPerformed

    private void ZonePrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZonePrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZonePrenomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenêtre_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Msg_Bienvenue;
    private javax.swing.JLabel Msg_Bye;
    private javax.swing.JTextArea Resultat;
    private javax.swing.JScrollPane Resultat0;
    private javax.swing.JTextField ZonePrenom;
    private javax.swing.JTextField ZoneSalaire;
    private javax.swing.JButton bouton_valide;
    private javax.swing.JLabel demandePrenom;
    private javax.swing.JLabel demandeSalaire;
    // End of variables declaration//GEN-END:variables
}
