/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_graphique_gouin;

/**
 *
 * @author gouin
 */
public class Fenêtre_Principale extends javax.swing.JFrame {

    /**
     * Creates new form Fenêtre_Principale
     */
    public Fenêtre_Principale() {
        initComponents();
        System.out.println("fenêtre créée");
        Msg_Bienvenue.setText("Bonjour le monde");
        Resultat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Msg_Bienvenue = new javax.swing.JLabel();
        Msg_Bye = new javax.swing.JLabel();
        bouton_valide = new javax.swing.JButton();
        ZoneNom = new javax.swing.JTextField();
        Demande = new javax.swing.JLabel();
        Resultat = new javax.swing.JLabel();
        demandeSalaire = new javax.swing.JLabel();
        Salaire = new javax.swing.JTextField();
        AugmenterSalaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Msg_Bienvenue.setText("Hello Word");

        Msg_Bye.setText("Bye Bye !!!");

        bouton_valide.setText("Cliquez !!!!!!");
        bouton_valide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_valideActionPerformed(evt);
            }
        });

        ZoneNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoneNomActionPerformed(evt);
            }
        });

        Demande.setText("Entrez votre prénom :");

        Resultat.setText("Résultat :");

        demandeSalaire.setText("Entrez votre salaire :");

        Salaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaireActionPerformed(evt);
            }
        });

        AugmenterSalaire.setText("TOUJOURS PLUS !");
        AugmenterSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugmenterSalaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bouton_valide)
                    .addComponent(Msg_Bye)
                    .addComponent(Msg_Bienvenue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(demandeSalaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AugmenterSalaire)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Resultat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Demande)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZoneNom, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Msg_Bienvenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZoneNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Demande))
                .addGap(45, 45, 45)
                .addComponent(bouton_valide)
                .addGap(28, 28, 28)
                .addComponent(Resultat)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(demandeSalaire)
                    .addComponent(Salaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AugmenterSalaire))
                .addGap(25, 25, 25)
                .addComponent(Msg_Bye)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_valideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_valideActionPerformed
        // TODO add your handling code here:
        Msg_Bye.setText("Bonne fin de journée !");
        String a = ZoneNom.getText();
        Resultat.setText("Bonjour mon brave " + a);
        Resultat.setVisible(true);
    }//GEN-LAST:event_bouton_valideActionPerformed

    private void ZoneNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoneNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZoneNomActionPerformed

    private void SalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaireActionPerformed

    private void AugmenterSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugmenterSalaireActionPerformed
        // TODO add your handling code here:
         String salaire = Salaire.getText();
        int salaire_entier = Integer.parseInt(salaire);
        salaire_entier++;
        Salaire.setText(salaire_entier + "");
    }//GEN-LAST:event_AugmenterSalaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenêtre_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AugmenterSalaire;
    private javax.swing.JLabel Demande;
    private javax.swing.JLabel Msg_Bienvenue;
    private javax.swing.JLabel Msg_Bye;
    private javax.swing.JLabel Resultat;
    private javax.swing.JTextField Salaire;
    private javax.swing.JTextField ZoneNom;
    private javax.swing.JButton bouton_valide;
    private javax.swing.JLabel demandeSalaire;
    // End of variables declaration//GEN-END:variables
}
